## Feature Extraction and  Data Preprocessing

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Merged_Data.csv")
df.head()

,Unnamed: 0,Stock,sentiment_score,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,sentiment_score_average
0,0,AAPL,0.104167,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917
1,1,AAPL,0.141667,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917
2,2,AAPL,0.104167,2024-11-22,228.059998,230.720001,228.059998,229.869995,38168300.0,0.00,0.0,0.104167
3,3,AAPL,0.104167,2024-11-15,226.399994,226.919998,224.270004,225.000000,47923700.0,0.00,0.0,0.104167
4,4,AAPL,0.104167,2024-11-08,227.169998,228.660004,226.410004,226.960007,38328800.0,0.25,0.0,0.113826

In [6]:
df=pd.read_csv("Data_with_content.csv")
df.head()

,Unnamed: 0,Content,Stock,sentiment_score,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,sentiment_score_average
0,0,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917
1,1,Old IRA very overweight in two equities - opin...,AAPL,0.141667,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917
2,2,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-22,228.059998,230.720001,228.059998,229.869995,38168300.0,0.00,0.0,0.104167
3,3,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-15,226.399994,226.919998,224.270004,225.000000,47923700.0,0.00,0.0,0.104167
4,4,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-08,227.169998,228.660004,226.410004,226.960007,38328800.0,0.25,0.0,0.113826

In [7]:
df.Stock.unique()

array(['AAPL', 'MSFT', 'AMZN', 'TSLA', 'GOOGL'], dtype=object)

In [8]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [9]:
df.head()

,Content,Stock,sentiment_score,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,sentiment_score_average
0,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917
1,Old IRA very overweight in two equities - opin...,AAPL,0.141667,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917
2,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-22,228.059998,230.720001,228.059998,229.869995,38168300.0,0.00,0.0,0.104167
3,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-15,226.399994,226.919998,224.270004,225.000000,47923700.0,0.00,0.0,0.104167
4,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-08,227.169998,228.660004,226.410004,226.960007,38328800.0,0.25,0.0,0.113826

### Extracting Subjectivity of each post

In [10]:
from textblob import TextBlob

# Add sentiment features
def extract_sentiment(content):
    analysis = TextBlob(content)
    return pd.Series({
        # Sentiment polarity (-1 to 1)
        'subjectivity': analysis.subjectivity  # Subjectivity (0 to 1)
    })

# Apply the function to the Content column
df[ 'subjectivity'] = df['Content'].apply(extract_sentiment)

In [11]:
df.head()

,Content,Stock,sentiment_score,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,sentiment_score_average,subjectivity
0,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917,0.225000
1,Old IRA very overweight in two equities - opin...,AAPL,0.141667,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917,0.341667
2,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-22,228.059998,230.720001,228.059998,229.869995,38168300.0,0.00,0.0,0.104167,0.225000
3,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-15,226.399994,226.919998,224.270004,225.000000,47923700.0,0.00,0.0,0.104167,0.225000
4,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-08,227.169998,228.660004,226.410004,226.960007,38328800.0,0.25,0.0,0.113826,0.225000

## Topic Modelling on posts using LDA model

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

vectorizer = CountVectorizer(max_features=500, stop_words='english')
content_matrix = vectorizer.fit_transform(df['Content'])

#LDA model
lda = LatentDirichletAllocation(n_components=5, random_state=42)  # 5 topics
lda_features = lda.fit_transform(content_matrix)
for i in range(lda_features.shape[1]):
    df[f'topic_{i}'] = lda_features[:, i]

In [13]:
df11=df

In [19]:
df1=df11

In [20]:
df2=df11

In [21]:
df3=df11

### Five topics are identified and added to the dataframe

In [14]:
df.head()

,Content,Stock,sentiment_score,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,sentiment_score_average,subjectivity,topic_0,topic_1,topic_2,topic_3,topic_4
0,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917,0.225000,0.969128,0.007718,0.007754,0.007698,0.007703
1,Old IRA very overweight in two equities - opin...,AAPL,0.141667,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917,0.341667,0.079900,0.013368,0.471801,0.138068,0.296863
2,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-22,228.059998,230.720001,228.059998,229.869995,38168300.0,0.00,0.0,0.104167,0.225000,0.969128,0.007716,0.007752,0.007698,0.007706
3,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-15,226.399994,226.919998,224.270004,225.000000,47923700.0,0.00,0.0,0.104167,0.225000,0.969109,0.007715,0.007753,0.007703,0.007720
4,r/Stocks Daily Discussion & Fundamentals Frida...,AAPL,0.104167,2024-11-08,227.169998,228.660004,226.410004,226.960007,38328800.0,0.25,0.0,0.113826,0.225000,0.967903,0.008018,0.008061,0.008006,0.008011

In [15]:
df.drop('Content',axis=1,inplace=True)

In [16]:
df.head()

,Stock,sentiment_score,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,sentiment_score_average,subjectivity,topic_0,topic_1,topic_2,topic_3,topic_4
0,AAPL,0.104167,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917,0.225000,0.969128,0.007718,0.007754,0.007698,0.007703
1,AAPL,0.141667,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917,0.341667,0.079900,0.013368,0.471801,0.138068,0.296863
2,AAPL,0.104167,2024-11-22,228.059998,230.720001,228.059998,229.869995,38168300.0,0.00,0.0,0.104167,0.225000,0.969128,0.007716,0.007752,0.007698,0.007706
3,AAPL,0.104167,2024-11-15,226.399994,226.919998,224.270004,225.000000,47923700.0,0.00,0.0,0.104167,0.225000,0.969109,0.007715,0.007753,0.007703,0.007720
4,AAPL,0.104167,2024-11-08,227.169998,228.660004,226.410004,226.960007,38328800.0,0.25,0.0,0.113826,0.225000,0.967903,0.008018,0.008061,0.008006,0.008011

### One-hot encoding Stock Name column

In [22]:
df1 = pd.get_dummies(df1, columns=['Stock'])

In [24]:
df1.head(60)

,sentiment_score,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,sentiment_score_average,...,topic_0,topic_1,topic_2,topic_3,topic_4,Stock_AAPL,Stock_AMZN,Stock_GOOGL,Stock_MSFT,Stock_TSLA
0,0.104167,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.0000,0.0,0.122917,...,0.969128,0.007718,0.007754,0.007698,0.007703,1,0,0,0,0
1,0.141667,2024-11-29,234.809998,237.809998,233.970001,237.330002,28481400.0,0.0000,0.0,0.122917,...,0.079900,0.013368,0.471801,0.138068,0.296863,1,0,0,0,0
2,0.104167,2024-11-22,228.059998,230.720001,228.059998,229.869995,38168300.0,0.0000,0.0,0.104167,...,0.969128,0.007716,0.007752,0.007698,0.007706,1,0,0,0,0
3,0.104167,2024-11-15,226.399994,226.919998,224.270004,225.000000,47923700.0,0.0000,0.0,0.104167,...,0.969109,0.007715,0.007753,0.007703,0.007720,1,0,0,0,0
4,0.104167,2024-11-08,227.169998,228.660004,226.410004,226.960007,38328800.0,0.2500,0.0,0.113826,...,0.967903,0.008018,0.008061,0.008006,0.008011,1,0,0,0,0
5,0.123485,2024-11-08,227.169998,228.660004,226.410004,226.960007,38328800.0,0.2500,0.0,0.113826,...,0.012603,0.012624,0.012548,0.012574,0.949650,1,0,0,0,0
6,0.000000,2024-11-02,225.559287,227.770589,224.814484,225.886261,45065775.0,0.1875,0.0,0.131754,...,0.016667,0.016771,0.016679,0.932946,0.016937,1,0,0,0,0
7,0.148889,2024-11-02,223.948576,226.881174,223.218965,224.812515,51802750.0,0.1250,0.0,0.131754,...,0.007417,0.007620,0.007439,0.969900,0.007624,1,0,0,0,0
8,0.246372,2024-11-02,222.337865,225.991759,221.623445,223.738770,58539725.0,0.0625,0.0,0.131754,...,0.022223,0.185656,0.022389,0.022834,0.746897,1,0,0,0,0
9,0.104167,2024-11-01,220.727153,225.102345,220.027926,222.665024,65276700.0,0.0000,0.0,0.104167,...,0.967903,0.008018,0.008061,0.008006,0.008011,1,0,0,0,0
10,-0.007143,2024-10-28,233.063595,234.472034,232.294437,233.143494,36087100.0,0.0000,0.0,-0.007143,...,0.011765,0.353329,0.084971,0.537856,0.012079,1,0,0,0,0
11,0.104167,2024-10-25,229.487523,232.963694,229.317711,231.155685,38802300.0,0.0000,0.0,0.104167,...,0.969113,0.007716,0.007755,0.007698,0.007718,1,0,0,0,0
12,0.266667,2024-10-24,229.727257,230.566345,228.158990,230.316620,31109500.0,0.0000,0.0,0.266667,...,0.084962,0.010640,0.010662,0.010664,0.883073,1,0,0,0,0
13,0.487500,2024-10-20,232.823841,233.243385,230.955901,232.529175,38770500.0,0.0000,0.0,0.487500,...,0.012879,0.948849,0.012690,0.012576,0.013006,1,0,0,0,0
14,0.187500,2024-10-18,235.920426,235.920426,233.752812,234.741730,46431500.0,0.0000,0.0,0.140589,...,0.009127,0.009308,0.009339,0.009296,0.962930,1,0,0,0,0
15,0.104167,2024-10-18,235.920426,235.920426,233.752812,234.741730,46431500.0,0.0000,0.0,0.140589,...,0.969119,0.007708,0.007759,0.007704,0.007710,1,0,0,0,0
16,0.130101,2024-10-18,235.920426,235.920426,233.752812,234.741730,46431500.0,0.0000,0.0,0.140589,...,0.220134,0.012467,0.011999,0.377148,0.378253,1,0,0,0,0
17,0.104167,2024-10-11,229.048004,229.157883,227.090151,227.299927,31759200.0,0.0000,0.0,0.104167,...,0.969093,0.007721,0.007772,0.007711,0.007703,1,0,0,0,0
18,-0.600000,2024-10-09,224.982474,229.497511,224.582920,229.287735,33591100.0,0.0000,0.0,-0.600000,...,0.015385,0.937972,0.015558,0.015586,0.015500,1,0,0,0,0
19,0.104167,2024-10-04,227.649533,227.749429,223.883687,226.550751,37245100.0,0.0000,0.0,0.104167,...,0.967901,0.008017,0.008065,0.008006,0.008011,1,0,0,0,0
20,0.333333,2024-10-01,229.267771,229.397617,223.494124,225.961411,63285000.0,0.0000,0.0,0.187500,...,0.025821,0.356758,0.255384,0.336716,0.025320,1,0,0,0,0
21,0.000000,2024-10-01,229.267771,229.397617,223.494124,225.961411,63285000.0,0.0000,0.0,0.187500,...,0.069295,0.009197,0.009232,0.150127,0.762150,1,0,0,0,0
22,0.083333,2024-10-01,229.267771,229.397617,223.494124,225.961411,63285000.0,0.0000,0.0,0.187500,...,0.011780,0.011983,0.011813,0.012067,0.952357,1,0,0,0,0
23,0.333333,2024-10-01,229.267771,229.397617,223.494124,225.961411,63285000.0,0.0000,0.0,0.187500,...,0.098427,0.010328,0.010271,0.409461,0.471512,1,0,0,0,0
24,0.104167,2024-09-27,228.208935,229.267767,227.050206,227.539658,34026000.0,0.0000,0.0,0.132083,...,0.969125,0.007717,0.007753,0.007698,0.007707,1,0,0,0,0
25,0.160000,2024-09-27,228.208935,229.267767,227.050206,227.539658,34026000.0,0.0000,0.0,0.132083,...,0.010543,0.010597,0.010529,0.174660,0.793671,1,0,0,0,0
26,0.700000,2024-09-21,228.963099,231.050798,227.210022,227.744431,176352950.0,0.0000,0.0,0.700000,...,0.012623,0.012571,0.012539,0.012855,0.949413,1,0,0,0,0
27,0.104167,2024-09-20,229.717263,232.833829,227.369839,227.949203,318679900.0,0.0000,0.0,0.088294,...,0.969016,0.007725,0.007766,0.007717,0.007775,1,0,0,0,0
28,0.160714,2024-09-20,229.717263,232.833829,227.369839,227.949203,318679900.0,0.0000,0.0,0.088294,...,0.011816,0.076155,0.011916,0.888036,0.012078,1,0,0,0,0
29,0.000000,2024-09-20,229.717263,232.833829,227.369839,227.949203,318679900.0,0.0000,0.0,0.088294,...,0.015385,0.015421,0.015387,0.015622,0.938184,1,0,0,0,0
30,0.546591,2024-09-16,216.302020,216.981280,213.684904,216.082275,59357400.0,0.0000,0.0,0.546591,...,0.006947,0.006987,0.972201,0.006936,0.006929,1,0,0,0,0
31,0.138889,2024-09-15,219.818156,220.387529,217.675517,219.168877,48062000.0,0.0000,0.0,0.138889,...,0.149987,0.773692,0.025075,0.025706,0.025539,1,0,0,0,0
32,0.104167,2024-09-13,223.334293,223.793779,221.666130,222.255478,36766600.0,0.0000,0.0,0.104167,...,0.969079,0.007728,0.007779,0.007706,0.007708,1,0,0,0,0
33,0.546591,2024-09-10,218.679408,221.236593,216.491813,219.868103,51591000.0,0.0000,0.0,-0.026705,...,0.007265,0.007229,0.970866,0.007253,0.007387,1,0,0,0,0
34,-0.600000,2024-09-10,218.679408,221.236593,216.491813,219.868103,51591000.0,0.0000,0.0,-0.026705,...,0.014286,0.942256,0.014451,0.014632,0.014376,1,0,0,0,0
35,0.116667,2024-09-08,221.191645,223.114532,218.010148,220.222717,50007000.0,0.0000,0.0,0.116667,...,0.112028,0.316262,0.297315,0.015847,0.258547,1,0,0,0,0
36,0.104167,2024-09-06,223.703881,224.992472,219.528482,220.577332,48423000.0,0.0000,0.0,0.104167,...,0.967900,0.008019,0.008064,0.008006,0.008011,1,0,0,0,0
37,-0.241667,2024-09-04,221.416407,221.536270,217.240993,220.607300,43840200.0,0.0000,0.0,-0.241667,...,0.022222,0.022768,0.022240,0.910505,0.022265,1,0,0,0,0
38,0.104167,2024-08-30,229.937031,230.146792,227.230003,228.748337,52990800.0,0.0000,0.0,0.104167,...,0.969105,0.007707,0.007755,0.007708,0.007725,1,0,0,0,0
39,0.546591,2024-08-27,225.751621,228.598495,224.642840,227.779388,35934600.0,0.0000,0.0,0.546591,...,0.007256,0.007206,0.971170,0.007182,0.007185,1,0,0,0,0
40,0.104167,2024-08-23,225.412002,227.969186,224.083462,226.590698,38677300.0,0.0000,0.0,0.104167,...,0.969114,0.007716,0.007756,0.007708,0.007707,1,0,0,0,0
41,0.020833,2024-08-21,226.271063,227.729450,224.802677,226.151184,34765500.0,0.0000,0.0,0.180278,...,0.011866,0.012233,0.011968,0.261831,0.702102,1,0,0,0,0
42,0.400000,2024-08-21,226.271063,227.729450,224.802677,226.151184,34765500.0,0.0000,0.0,0.180278,...,0.010000,0.222963,0.010068,0.159948,0.597020,1,0,0,0,0
43,0.120000,2024-08-21,226.271063,227.729450,224.802677,226.151184,34765500.0,0.0000,0.0,0.180278,...,0.013536,0.013389,0.013402,0.013411,0.946262,1,0,0,0,0
44,0.104167,2024-08-16,223.673911,226.580716,223.404203,225.801575,44340200.0,0.0000,0.0,0.104167,...,0.969120,0.007716,0.007754,0.007706,0.007703,1,0,0,0,0
45,0.316667,2024-08-14,220.327604,222.784892,219.458549,221.476334,41960600.0,0.0000,0.0,0.316667,...,0.012575,0.949262,0.012566,0.012755,0.012841,1,0,0,0,0
46,0.104167,2024-08-09,211.621971,216.291416,211.492259,215.752640,42201600.0,0.0000,0.0,0.104167,...,0.967905,0.008016,0.008061,0.008006,0.008012,1,0,0,0,0
47,-0.413889,2024-08-05,198.641276,213.018802,195.558244,208.798340,119548600.0,0.0000,0.0,-0.413889,...,0.011765,0.219333,0.127885,0.012202,0.628815,1,0,0,0,0
48,0.120000,2024-08-02,218.656065,225.091540,217.219323,219.364471,105568600.0,0.0000,0.0,0.074722,...,0.011480,0.011420,0.011549,0.011342,0.954209,1,0,0,0,0
49,0.000000,2024-08-02,218.656065,225.091540,217.219323,219.364471,105568600.0,0.0000,0.0,0.074722,...,0.964988,0.008729,0.008765,0.008723,0.008795,1,0,0,0,0
50,0.104167,2024-08-02,218.656065,225.091540,217.219323,219.364471,105568600.0,0.0000,0.0,0.074722,...,0.969117,0.007722,0.007754,0.007703,0.007703,1,0,0,0,0
51,0.000000,2024-08-01,223.864292,223.974045,216.530867,217.867844,62501000.0,0.0000,0.0,-0.059970,...,0.009138,0.009317,0.009109,0.963330,0.009107,1,0,0,0,0
52,-0.129167,2024-08-01,223.864292,223.974045,216.530867,217.867844,62501000.0,0.0000,0.0,-0.059970,...,0.009112,0.009158,0.009092,0.963327,0.009310,1,0,0,0,0
53,0.000000,2024-08-01,223.864292,223.974045,216.530867,217.867844,62501000.0,0.0000,0.0,-0.059970,...,0.964988,0.008729,0.008765,0.008723,0.008795,1,0,0,0,0
54,-0.110714,2024-08-01,223.864292,223.974045,216.530867,217.867844,62501000.0,0.0000,0.0,-0.059970,...,0.008716,0.008760,0.052038,0.921580,0.008906,1,0,0,0,0
55,0.104167,2024-07-26,218.207072,218.995300,215.523133,217.468750,41601300.0,0.0000,0.0,0.104167,...,0.969131,0.007710,0.007755,0.007700,0.007704,1,0,0,0,0
56,0.104167,2024-07-19,224.313288,226.288821,222.776751,223.804428,49151500.0,0.0000,0.0,0.104167,...,0.969127,0.007708,0.007755,0.007703,0.007707,1,0,0,0,0
57,0.200000,2024-07-17,228.932843,230.938323,226.129179,228.364136,57345900.0,0.0000,0.0,0.130612,...,0.033334,0.033886,0.033620,0.864666,0.034496,1,0,0,0,0
58,0.061224,2024-07-17,228.932843,230.938323,226.129179,228.364136,57345900.0,0.0000,0.0,0.130612,...,0.075732,0.012786,0.081364,0.012832,0.817286,1,0,0,0,0
59,0.000000,2024-07-16,234.470328,235.737470,231.806348,234.290741,43234300.0,0.0000,0.0,0.000000,...,0.020172,0.919154,0.020222,0.020160,0.020291,1,0,0,0,0

In [25]:
df1.to_csv("preprocessed_data.csv",index=False)

### Formatting the Date Time column to use in our ML model effectively

In [28]:
df1['Date'] = pd.to_datetime(df1['Date'])
# Extracting from Date time column

df1['Year'] = df1['Date'].dt.year
df1['Month'] = df1['Date'].dt.month
df1['Day'] = df1['Date'].dt.day
df1['Weekday'] = df1['Date'].dt.weekday  # 0 = Monday, 6 = Sunday
df1['Quarter'] = df1['Date'].dt.quarter
df1 = df1.drop(columns=['Date'])
print(df1.head())

   sentiment_score        Open        High         Low       Close  \
0         0.104167  234.809998  237.809998  233.970001  237.330002
1         0.141667  234.809998  237.809998  233.970001  237.330002
2         0.104167  228.059998  230.720001  228.059998  229.869995
3         0.104167  226.399994  226.919998  224.270004  225.000000
4         0.104167  227.169998  228.660004  226.410004  226.960007

       Volume  Dividends  Stock Splits  sentiment_score_average  subjectivity  \
0  28481400.0       0.00           0.0                 0.122917      0.225000
1  28481400.0       0.00           0.0                 0.122917      0.341667
2  38168300.0       0.00           0.0                 0.104167      0.225000
3  47923700.0       0.00           0.0                 0.104167      0.225000
4  38328800.0       0.25           0.0                 0.113826      0.225000

   ...  Stock_AAPL  Stock_AMZN  Stock_GOOGL  Stock_MSFT  Stock_TSLA  Year  \
0  ...           1           0            0           0           0  2024
1  ...           1           0            0           0           0  2024
2  ...           1           0            0           0           0  2024
3  ...           1           0            0           0           0  2024
4  ...           1           0            0           0           0  2024

   Month  Day  Weekday  Quarter
0     11   29        4        4
1     11   29        4        4
2     11   22        4        4
3     11   15        4        4
4     11    8        4        4

[5 rows x 25 columns]

In [33]:
df1.to_csv("Preprocessed_final_data.csv",index=False)

### Preprocessed Final Data

In [32]:
df1.head()

,sentiment_score,Open,High,Low,Close,Volume,Dividends,Stock Splits,sentiment_score_average,subjectivity,...,Stock_AAPL,Stock_AMZN,Stock_GOOGL,Stock_MSFT,Stock_TSLA,Year,Month,Day,Weekday,Quarter
0,0.104167,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917,0.225000,...,1,0,0,0,0,2024,11,29,4,4
1,0.141667,234.809998,237.809998,233.970001,237.330002,28481400.0,0.00,0.0,0.122917,0.341667,...,1,0,0,0,0,2024,11,29,4,4
2,0.104167,228.059998,230.720001,228.059998,229.869995,38168300.0,0.00,0.0,0.104167,0.225000,...,1,0,0,0,0,2024,11,22,4,4
3,0.104167,226.399994,226.919998,224.270004,225.000000,47923700.0,0.00,0.0,0.104167,0.225000,...,1,0,0,0,0,2024,11,15,4,4
4,0.104167,227.169998,228.660004,226.410004,226.960007,38328800.0,0.25,0.0,0.113826,0.225000,...,1,0,0,0,0,2024,11,8,4,4